apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app:  simple-bank-api
    spec:
      containers:
        - name: nginx
          image:
          ports:
            - containerPort: 80
