apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: nginx
          image: 743739442960.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:c681657b391a9df9fd407e4ac236deb57e7e5c4c
          ports:
            - containerPort: 8080
